-- Suppression de la table CHARACTERS
DROP TABLE characters;

-- Création de la table CHARACTERS
CREATE TABLE characters (
    character_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    character_name VARCHAR2(100) NOT NULL,
    CONSTRAINT pk_characters PRIMARY KEY (character_id)
);

-- Insertion de 2 lignes
INSERT INTO characters (character_name) VALUES ('zadazd');
INSERT INTO characters (character_name) VALUES ('Nyx');

-- Validation des insertions
COMMIT;