-- Suppression de la table MENUS
DROP TABLE menus;

-- Création de la table MENUS
CREATE TABLE menus (
    menu_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    menu_name_en VARCHAR2(100) NOT NULL,
    menu_name_fr VARCHAR2(100),

    CONSTRAINT pk_menus PRIMARY KEY (menu_id)
);

-- Insertion de 2 lignes
INSERT INTO menus (menu_name_en, menu_name_fr) VALUES ('Home', 'Accueil');
INSERT INTO menus (menu_name_en, menu_name_fr) VALUES ('Settings', 'Paramètres');
INSERT INTO menus (menu_name_en, menu_name_fr) VALUES ('Game', 'Jeu');
INSERT INTO menus (menu_name_en, menu_name_fr) VALUES ('About', 'À propos');
INSERT INTO menus (menu_name_en, menu_name_fr) VALUES ('Contact', 'Contact');
INSERT INTO menus (menu_name_en, menu_name_fr) VALUES ('My Account', 'Mon Compte');
INSERT INTO menus (menu_name_en, menu_name_fr) VALUES ('English', 'Anglais');
INSERT INTO menus (menu_name_en, menu_name_fr) VALUES ('French', 'Français');

-- Validation des insertions
COMMIT;